### ISSUE TITLE
Plugin not resetting correctly in between games.

### ISSUE THREAD

**Issue by MikeFoden** [RedHatter/Graveyard#12]
I've noticed each game I play, that the graveyard list does not reset correctly in between games.

**Comment by RedHatter** [comment]
This is fixed in master.

**Comment by MikeFoden** [comment]
My apologies @RedHatter - I did not see it was fixed but not released yet. :)

**Comment by Arumba07** [comment]
@RedHatter I apologize for being a complete newb to git, but is there a way to use the latest commits since 1.1?  When I try to download the 1.1 release I am still getting the active graveyards between games, and I've also noticed that in the settings for Graveyard it still calls itself version 1.0.0.  This lead me to believe perhaps there was an issue with the download links, but I tried using the 1.0.0 release and that wasn't any different.  I've tried downloading the master as a zip, but that gives me a completely different set of files, with no Graveyard.dll to be found...

How can I fix it so it works better..?
